name = "anonbot"
main = "src/index.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "anonbot-db"
database_id = "برو خونتون اینا شخصیه"  
[[kv_namespaces]]
binding = "CACHE"
id = "اینم شخصیه بی تربیت"
